"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import FooterPage from "./footer/Page";
import Subcribe from "@/components/Home/Subcribe";
import { CartProvider } from "@/components/context/CartContext"; //Import the CartProvider
// import store from "@/store/store";
// import { Provider } from "react-redux";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Eco Bazar",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <CartProvider>
          <Navbar />

          {/* <Provider store={store}> */}
          <main className="flex-1">{children}</main>
          {/* </Provider> */}
          <Subcribe />
          <FooterPage />
        </CartProvider>
      </body>
    </html>
  );
}
