import React from "react";
import Home from "@/components/Home/Home";

export const metadata = {
  title: "Eco Bazar",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <Home />
    </div>
  );
}
